### ISSUE TITLE
not enough arguments in call to inertia.NewWithFS 	

### ISSUE THREAD

**Issue by neilyoung** [petaki/satellite#16]
# github.com/petaki/satellite/internal/web
internal/web/serve.go:156:66: not enough arguments in call to inertia.NewWithFS
	have (string, string, string, embed.FS)
	want (string, string, string, fs.FS, string)

Most likely easy to solve

**Comment by petaki** [comment]
Hi! I can't reproduce this error in manual compile or in Docker.

Probably because the original `inertia.NewWithFS` method does not have a 5th parameter.
https://github.com/petaki/inertia-go/blob/master/inertia.go#L40

Is it possible to use a fork from the `inertia-go` lib?
